# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/biodigital-inc/human-ios-sdk.git'

target 'HumanObjCApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HumanObjCApp
  pod 'HumanKit', '165.5-universal'

end
