# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/biodigital-inc/human-ios-sdk.git'

target 'HumanSwiftApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HumanSwiftApp
  pod 'HumanKit', '140.1'

end
