#if 0
#elif (defined(__arm64__) && __arm64__) || (defined(__x86_64__) && __x86_64__)
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HumanKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

/// Enumerated background option possible values
typedef SWIFT_ENUM(NSInteger, BackgroundOptions, open) {
/// a circular gradient from the center to the outside of the screen
  BackgroundOptionsRadial = 0,
/// a linear gradient from the top to the bottom of the screen
  BackgroundOptionsLinear = 1,
};




/// The HKAnnotation object represents an object annotation in the scene
SWIFT_CLASS("_TtC8HumanKit12HKAnnotation")
@interface HKAnnotation : NSObject
/// objectID of the annotated object
/// this is required, all annotations must be connected to an object
@property (nonatomic, copy) NSString * _Nonnull objectId;
/// annotation title
@property (nonatomic, copy) NSString * _Nonnull title;
/// annotation description text
@property (nonatomic, copy) NSString * _Nonnull text;
/// annotation ID for reference
@property (nonatomic, copy) NSString * _Nonnull annotationId;
/// world position [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull position;
/// screen position [x,y] of the annotation
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull canvasPosition;
/// label offset [x,y] from the object can be used to enhance visibility
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull labelOffset;
/// whether or not the annotation is currently visible
/// this will get set to false if the annotation moves off screen or is occluded
@property (nonatomic) BOOL shown;
/// whether or not the annotation is occludable
@property (nonatomic) BOOL occludable;
/// Create an HKAnnotation with the ID of its object
/// \param objectId Id of the attached object
///
- (nonnull instancetype)initWithObjectId:(NSString * _Nonnull)objectId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// HKAnnotations manages object annotations in the scene
/// since:
/// SDK 2.0
SWIFT_CLASS("_TtC8HumanKit13HKAnnotations")
@interface HKAnnotations : NSObject
/// A map of annotation IDs to HKAnnotation objects in the current scene
@property (nonatomic, copy) NSDictionary<NSString *, HKAnnotation *> * _Nonnull annotations;
/// Shows the annotations in the current scene
- (void)show;
/// Hides the annotations in the scene
/// This allows apps to draw native annotations over the view
- (void)hide;
/// Create an annotation in the scene with an HKAnnotation object.
/// since:
/// SDK 2.0
/// \param annotation set up an HKAnnotation object and pass it to this function to add it to the scene
///
- (void)createWithAnnotation:(HKAnnotation * _Nonnull)annotation;
/// Update an annotation in the scene with an updated HKAnnotation object.
/// since:
/// SDK 2.0
/// \param annotationId Id of the updated annotation to update in the scene
///
- (void)updateWithAnnotationId:(NSString * _Nonnull)annotationId;
/// Delete an annotation in the scene
/// since:
/// SDK 2.0
/// \param annotationId Id of the annotation to remove from the scene
///
- (void)destroyWithAnnotationId:(NSString * _Nonnull)annotationId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Camera object
SWIFT_CLASS("_TtC8HumanKit8HKCamera")
@interface HKCamera : NSObject
/// Camera position [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull eye;
/// Look vector [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull look;
/// Up vector [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull up;
/// The current zoom factor of the camera
@property (nonatomic) double zoomFactor;
/// Get current camera information. (eye, look, up, and zoom)
/// Queries the scene asynchronously and sets local variables in the Camera object
/// Triggers camera.updated callback
/// Deprecated in API 2.0 as this information is directly accessible in this object and always up to date
- (void)getCameraInfo SWIFT_UNAVAILABLE_MSG("camera info is directly accessible and always up to date");
/// Reset camera to original position
/// since:
/// SDK 2.0
- (void)reset;
/// Pan camera by offset in world space.
/// \param x offset on x axis
///
/// \param y offset on y axis
///
/// \param z offset on z axis
///
- (void)panWithX:(float)x y:(float)y z:(float)z;
/// Zoom the camera in and out of its point of focus.
/// <ul>
///   <li>
///     : Zoom factor between 0 and 1
///   </li>
/// </ul>
- (void)zoom:(double)factor;
/// Orbit around camera’s current point of focus.
/// \param yaw Yaw angle (degrees)
///
/// \param pitch Pitch angle (degrees)
///
/// \param duration Time of orbit animation (seconds)
///
- (void)orbitWithYaw:(float)yaw pitch:(float)pitch duration:(float)duration;
/// Move the camera, all values are optional
/// \param eyeIn The new camera postion.
///
/// \param lookIn The new camera look vector.
///
/// \param upIn The new camera up vector.
///
/// \param animated If true, camera will animate from current position to new position, default is true
///
- (void)setWithEyeIn:(NSArray<NSNumber *> * _Nullable)eyeIn lookIn:(NSArray<NSNumber *> * _Nullable)lookIn upIn:(NSArray<NSNumber *> * _Nullable)upIn animated:(BOOL)animated;
/// Updates camera position.
/// \param eyeIn The new camera position
///
/// \param lookIn The new camera look vector.
///
/// \param upIn The new camera up vector.
///
/// \param animated If true, camera will animate from current position to new position
/// Deprecated for set()
///
- (void)updateCameraWithEyeIn:(NSArray<NSNumber *> * _Nonnull)eyeIn lookIn:(NSArray<NSNumber *> * _Nonnull)lookIn upIn:(NSArray<NSNumber *> * _Nonnull)upIn animated:(BOOL)animated SWIFT_DEPRECATED_MSG("Please use set(eyeIn:lookIn,upIn,animated:)");
/// Animates camera to object specified by its id.
/// \param objectId Object id specified by string
///
- (void)animateToObjectId:(NSString * _Nonnull)objectId;
/// Lock or unlock the camera rotation around the Y axis
/// attention:
/// This is no longer supported
/// \param lock boolean
///
- (void)lock:(BOOL)lock SWIFT_UNAVAILABLE_MSG("This is no longer supported");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// HKChapter object
SWIFT_CLASS("_TtC8HumanKit9HKChapter")
@interface HKChapter : NSObject
/// chapter title
@property (nonatomic, copy) NSString * _Nonnull title;
/// chapter description text
@property (nonatomic, copy) NSString * _Nonnull text;
/// chapter order, starts at 0
@property (nonatomic) NSInteger index;
/// true if this chapter is animated
/// since:
/// SDK 2.0
@property (nonatomic) BOOL animated;
/// true if this chapter contains audio
/// since:
/// SDK 2.0
@property (nonatomic) BOOL audio;
/// true if this chapter contains video
/// since:
/// SDK 2.0
@property (nonatomic) BOOL video;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

/// HKColor object for use with scene.colorObject()
SWIFT_CLASS("_TtC8HumanKit7HKColor")
@interface HKColor : NSObject
/// tint color as UIColor
@property (nonatomic, strong) UIColor * _Nonnull tint;
/// saturation -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat saturation;
/// opacity 0.0 to 1.0, default is 1.0
@property (nonatomic) CGFloat opacity;
/// brightness -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat brightness;
/// contrast -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat contrast;
/// Set all of the variables to random settings, for demonstration purposes
- (void)randomColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HKHumanDelegate;
@class HKScene;
@class HKTimeline;
@class HKUI;
@class UIView;
enum HumanUIOptions : NSInteger;

/// The BioDigital Human 3D View object and API
SWIFT_CLASS("_TtC8HumanKit7HKHuman")
@interface HKHuman : NSObject
/// The HKHumanDelegate object
/// <ul>
///   <li>
///     Set this to have access to the callback functions in your app
///   </li>
/// </ul>
@property (nonatomic, weak) id <HKHumanDelegate> _Nullable delegate;
/// HKScene object provides information and control of the 3D scene
@property (nonatomic, strong) HKScene * _Nonnull scene;
/// HKTimeline object controls Chapter navigation and animations
@property (nonatomic, strong) HKTimeline * _Nonnull timeline;
/// HKCamera object for manipulating the camera and reading camera information
@property (nonatomic, strong) HKCamera * _Nonnull camera;
/// HKUI object for setting and reading the UI parameters
@property (nonatomic, strong) HKUI * _Nonnull ui;
/// HKAnnotations object managing HKAnnotations in the scene
/// since:
/// SDK 2.0
@property (nonatomic, strong) HKAnnotations * _Nonnull annotations;
/// version of the 3D engine
@property (nonatomic, copy) NSString * _Nonnull version;
/// Initialize the Human Body with a view and the default UI options
/// note:
/// This is the recommended way to use HKHuman as of SDK 2.0
/// \param view the UIView to draw the 3D scene
///
- (nonnull instancetype)initWithView:(UIView * _Nonnull)view OBJC_DESIGNATED_INITIALIZER;
/// Set one UI variable to true or false
/// \param option a value from the enum HumanUIOptions
///
/// \param value true or false
///
- (void)setupUIWithOption:(enum HumanUIOptions)option value:(BOOL)value;
/// Loads a BioDigital Human 3D module.
/// \param model The moduleID string
///
/// \param callback A closure to run after the module is loaded
///
- (void)loadWithModel:(NSString * _Nonnull)model callback:(void (^ _Nonnull)(void))callback;
/// Unload a model if one is loaded
- (void)unload;
/// Disable user input
/// since:
/// SDK 2.0
- (void)disableInput;
/// Enable user input
/// since:
/// SDK 2.0
- (void)enableInput;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

/// The optional delegate callback functions
SWIFT_PROTOCOL("_TtP8HumanKit15HKHumanDelegate_")
@protocol HKHumanDelegate
@optional
/// Callback when the scene metadata is accessible
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param initScene the title of the loaded scene
///
- (void)human:(HKHuman * _Nonnull)view initScene:(NSString * _Nonnull)initScene;
/// Callback when the current animation has updated
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param timelineUpdated the updated timeline object
///
- (void)human:(HKHuman * _Nonnull)view timelineUpdated:(HKTimeline * _Nonnull)timelineUpdated;
/// Callback when the current animation is finished playing
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param animationComplete always true
///
- (void)human:(HKHuman * _Nonnull)view animationComplete:(BOOL)animationComplete;
/// Callback when an object has been picked by the user
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
/// \param position the world position (x,y,z) of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectPicked:(NSString * _Nonnull)objectPicked position:(NSArray<NSNumber *> * _Nonnull)position;
/// Callback when an object has been selected
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectSelected:(NSString * _Nonnull)objectSelected;
/// Callback when an object has been deselected
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectDeselected:(NSString * _Nonnull)objectDeselected;
/// Callback when a chapter has been loaded
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param chapterId the ID of the chapter, for lookup in the chapters map
///
- (void)human:(HKHuman * _Nonnull)view chapterTransition:(NSString * _Nonnull)chapterTransition;
/// Callback when the camera has been initialized or moved
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param cameraUpdated the updated HKCamera object
///
- (void)human:(HKHuman * _Nonnull)view cameraUpdated:(HKCamera * _Nonnull)cameraUpdated;
/// Callback when a xray mode is enabled or disabled
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param xrayEnabled Boolean indicating true for xray enabled or false for xray disabled
///
- (void)human:(HKHuman * _Nonnull)view xrayEnabled:(BOOL)xrayEnabled;
/// Callback when a call to scene.restore() has completed successfully
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param sceneRestored always true
///
- (void)human:(HKHuman * _Nonnull)view sceneRestored:(BOOL)sceneRestored;
/// Callback when visibility of scene objects has changed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectsShown a dictionary of object IDs and a boolean to indicate if the object is shown (true) or hidden (false)
///
- (void)human:(HKHuman * _Nonnull)view objectsShown:(NSDictionary<NSString *, NSNumber *> * _Nonnull)objectsShown;
/// Callback when the color of an object has been read from the scene
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectColor the ID of the object
///
/// \param color the color of the object
///
- (void)human:(HKHuman * _Nonnull)view objectColor:(NSString * _Nonnull)objectColor color:(HKColor * _Nonnull)color;
/// Callback when visibility of scene annotations has changed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationsShown a boolean to indicate if the annotations are shown (true) or hidden (false)
///
- (void)human:(HKHuman * _Nonnull)view annotationsShown:(BOOL)annotationsShown;
/// Callback when an annotation has been created
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationCreated the ID of the annotation
///
- (void)human:(HKHuman * _Nonnull)view annotationCreated:(NSString * _Nonnull)annotationCreated;
/// Callback when an annotation has been destroyed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationDestroyed the ID of the annotation
///
- (void)human:(HKHuman * _Nonnull)view annotationDestroyed:(NSString * _Nonnull)annotationDestroyed;
/// Callback when an annotation has moved on the screen
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationUpdated the updated HKAnnotation object
///
- (void)human:(HKHuman * _Nonnull)view annotationUpdated:(HKAnnotation * _Nonnull)annotationUpdated;
/// Callback when a screenshot has been generated
/// \param image the UIImage screenshot
///
- (void)screenshotWithImage:(UIImage * _Nonnull)image;
/// Callback when the scene metadata is accessible
/// Deprecated in SDK 2.0
- (void)onInitMessage SWIFT_DEPRECATED_MSG("Please use human(_:initScene:)");
/// Callback when a chapter has been loaded
/// Deprecated in SDK 2.0
/// \param chapterId the ID of the chapter, for lookup in the chapters map
///
/// \param view the HKHuman object in which the transition occurred
///
- (void)onChapterTransitionWithChapterId:(NSString * _Nonnull)chapterId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:chapterTransition:)");
/// Callback when an object has been deselected
/// Deprecated in SDK 2.0
/// \param objectId the ID of the deselected object
///
/// \param view the HKHuman object in which the object was selected
///
- (void)onObjectDeselectedWithObjectId:(NSString * _Nonnull)objectId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:objectDeselected:)");
/// Callback when an object has been selected
/// Deprecated in SDK 2.0
/// \param objectId the ID of the selected object
///
/// \param view the HKHuman object in which the object was selected
///
- (void)onObjectSelectedWithObjectId:(NSString * _Nonnull)objectId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:objectSelected:)");
/// Callback when the current animation is finished playing
/// Deprecated in SDK 2.0
- (void)onAnimationComplete SWIFT_DEPRECATED_MSG("Please use human(_:animationComplete:)");
@end


/// HKModel object
SWIFT_CLASS("_TtC8HumanKit7HKModel")
@interface HKModel : NSObject
/// ID of the model.  example: production/maleAdult/flu.json
@property (nonatomic, copy) NSString * _Nonnull modelId;
/// model title
@property (nonatomic, copy) NSString * _Nonnull title;
/// model text description
@property (nonatomic, copy) NSString * _Nonnull text;
/// url of thumbnail image
@property (nonatomic, copy) NSString * _Nonnull thumbnail;
/// initialize an HKModel
/// \param modelId the model ID, will look like “production/maleAdult/flu” or “E3W2”
///
/// \param title the title of the model
///
/// \param text the text description of the model
///
/// \param thumb optionally include the name or location of the thumbnail image
///
- (nonnull instancetype)initWithModelId:(NSString * _Nonnull)modelId title:(NSString * _Nonnull)title text:(NSString * _Nonnull)text thumb:(NSString * _Nonnull)thumb OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// HKScene manages the current scene and the scene objects
SWIFT_CLASS("_TtC8HumanKit7HKScene")
@interface HKScene : NSObject
/// The title of the current loaded scene.
@property (nonatomic, copy) NSString * _Nonnull title;
/// The text  description of the current loaded scene.
@property (nonatomic, copy) NSString * _Nonnull text;
/// The text description of the current loaded scene, if it is broken into sections
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nonnull textSections;
/// A flat unordered list of visible objects in the current scene
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull objectIds;
/// A map of objectIDs to display names
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull objects;
/// Brings up the built-in iOS share UI with the current contents of the view
- (void)shareFrom:(CGRect)from;
/// Captures a screenshot and triggers the screenshot callback in HKHumanDelegate
- (void)screenshot;
/// Reset the scene objects to the current scene’s original state
/// note:
/// This does not reset the camera, there is a separate function for that
- (void)reset;
/// Hide a group of obects by object ID
/// Groups of objects can be hidden by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to hide
///
- (void)hideWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Show a group of obects by object ID
/// Groups of objects can be shown by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to show
///
- (void)showWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Isolate a group of obects by object ID
/// Groups of objects can be shown by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to isolate
///
- (void)isolateWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Select a group of objects programatically
/// \param objectIds An array of object IDs to select
///
- (void)selectWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Deselect all objects in the scene
- (void)undoSelections;
/// Change the highlight color
/// \param color Selected objects are yellow by default, set this to use a different color
///
- (void)setHighlightColorWithColor:(UIColor * _Nonnull)color;
/// Change the object highlight color back to the original yellow color
- (void)resetHighlightColor;
/// Disable object highlighting
- (void)disableHighlight;
/// Enable object highlighting
- (void)enableHighlight;
/// Highlight an object even if highlight is disabled for the user
/// \param objectIds object to highlight
///
- (void)highlightWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// unhighlight an object
/// \param objectId object to unhighlight
///
- (void)unhighlightWithObjectId:(NSString * _Nonnull)objectId;
/// Prevent objects from being selected
- (void)disablePicking;
/// Allow objects to be selected
- (void)enablePicking;
/// Enables labels to appear when an object is selected, this is the default behavior, unless disabled
- (void)showLabels;
/// Hides all object labels and disables future labels from appearing on selected objects
- (void)hideLabels;
/// Turn xray mode ON or OFF in the current scene
/// \param enabled A boolean to turn xray mode ON or OFF
///
- (void)xray:(BOOL)enabled;
/// Get an object’s screen position
/// \param objectID A valid object ID string
///
///
/// returns:
/// the screen position of the center of the object with the given ID as [x,y]
- (NSArray<NSNumber *> * _Nonnull)getObjectPositionWithObjectID:(NSString * _Nonnull)objectID SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE_MSG("this is no longer supported.  please contact BioDigital if you require this functionality.");
/// Set the color of an object
- (void)colorWithObjectId:(NSString * _Nonnull)objectId color:(HKColor * _Nonnull)color;
/// Unset the color of a scene object
/// \param objectId object ID to uncolor
///
- (void)uncolorWithObjectId:(NSString * _Nonnull)objectId;
/// Get the color of a scene object
/// since:
/// SDK 2.0
/// Calls human(_:colorObject:color:) on success
/// \param objectId object ID to uncolor
///
- (void)getColorWithObjectId:(NSString * _Nonnull)objectId;
/// Move an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param translate [x,y,z] array amount to move the object]
///
- (void)translateObjectWithObjectId:(NSString * _Nonnull)objectId translate:(NSArray<NSNumber *> * _Nonnull)translate;
/// Rotate an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param rotate [x,y,z] array amount to rotate the object]
///
- (void)rotateObjectWithObjectId:(NSString * _Nonnull)objectId rotate:(NSArray<NSNumber *> * _Nonnull)rotate;
/// Scale an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param scale [x,y,z] array amount to scale the object]
///
- (void)scaleObjectWithObjectId:(NSString * _Nonnull)objectId scale:(NSArray<NSNumber *> * _Nonnull)scale;
/// Pivot an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param pivot [x,y,z] array amount to rotate the object]
///
- (void)pivotObjectWithObjectId:(NSString * _Nonnull)objectId pivot:(NSArray<NSNumber *> * _Nonnull)pivot;
/// Move an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param translate [x,y,z] array amount to move the object]
///
/// \param rotate [x,y,z] array amount to rotate the object]
///
/// \param scale [x,y,z] array amount to scale the object]
///
/// \param pivot [x,y,z] array amount to rotate the object]
///
- (void)transformObjectWithObjectId:(NSString * _Nonnull)objectId translate:(NSArray<NSNumber *> * _Nonnull)translate rotate:(NSArray<NSNumber *> * _Nonnull)rotate scale:(NSArray<NSNumber *> * _Nonnull)scale pivot:(NSArray<NSNumber *> * _Nonnull)pivot;
/// Capture the current state of the scene
/// since:
/// SDK 2.0
- (void)capture;
/// Restore the scene from the previous capture
/// Calls human(_:sceneRestored:) on success
/// since:
/// SDK 2.0
- (void)restore;
/// Select an object programatically
/// \param objectID the object you want to select
/// Deprecated in SDK 2.0.  Please use selectObjects(objectIds:) instead
///
- (void)selectObjectWithObjectID:(NSString * _Nonnull)objectID SWIFT_DEPRECATED_MSG("Please use select(objectIds:) instead");
/// Select an object programatically     - Parameter objectID: the object you want to select
/// Deprecated in SDK 2.0.  Please use selectObjects(objectIds:) instead
- (void)selectObjectWithGroupWithObjectID:(NSString * _Nonnull)objectID group:(NSArray<NSString *> * _Nonnull)group SWIFT_DEPRECATED_MSG("Please use select(objectIds:) instead");
/// Turn isolate mode ON or OFF in the current scene
/// This will isolate any selected objects and set the SDK to isolate any user selected object
/// \param enabled A boolean to turn isolate mode ON or OFF
///
- (void)isolate:(BOOL)enabled SWIFT_DEPRECATED_MSG("Please use isolate(objectIds:)");
/// Turn dissect mode ON or OFF in the current scene
/// \param enabled A boolean to turn dissect mode ON or OFF
///
- (void)dissect:(BOOL)enabled SWIFT_DEPRECATED_MSG("Please use hide(objectIds:)");
/// Undo the last dissect
/// Deprecated in API 2.0 use showObjects(objIds:) instead
- (void)undo SWIFT_DEPRECATED_MSG("Please use show(objectIds:)");
/// Set the color of an object
- (void)colorObjectWithId:(NSString * _Nonnull)id color:(HKColor * _Nonnull)color SWIFT_DEPRECATED_MSG("", "colorWithObjectId:color:");
/// Unset the color of a scene object
- (void)uncolorObjectWithId:(NSString * _Nonnull)id SWIFT_DEPRECATED_MSG("", "uncolorWithObjectId:");
/// unHighlight an object
/// \param objectId object to unhighlight
///
- (void)unhighlightObjectWithObjectid:(NSString * _Nonnull)objectid;
/// Check if an object is Xray
/// Removed in API 2.0, use getColor(id:) instead
- (BOOL)isXrayWithObjectID:(NSString * _Nonnull)objectID SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE_MSG("Please use getColor(objectId:) instead");
/// Set an object to Xray
/// Removed in API 2.0 - Set the object’s color instead
/// Our ’xray” color is brightness = 0.55, saturation = -1, and tint is UIColor(red:0.0, green: 0.0, blue: 0.0, alpha: 1.0)
- (void)setXrayWithObjectID:(NSString * _Nonnull)objectID enable:(BOOL)enable SWIFT_UNAVAILABLE_MSG("Please use colorObject instead");
/// Set an object to unpickable
/// Removed in API 2.0 - this is no longer supported
- (void)setPickableWithObjectID:(NSString * _Nonnull)objectID enable:(BOOL)enable SWIFT_UNAVAILABLE_MSG("This is not currently supported");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HKServicesDelegate;
enum HumanLanguage : NSInteger;

/// The BioDigital Human backend services
SWIFT_CLASS("_TtC8HumanKit10HKServices")
@interface HKServices : NSObject
/// Set the delegate for access to the callback functions
@property (nonatomic, weak) id <HKServicesDelegate> _Nullable delegate;
/// Modules fetched from the BioDigital servers are stored here
/// Providing a secret to the init function will trigger a fetch of modules associated with your account, the modulesLoaded callback will alert you when the module array is ready
@property (nonatomic, copy) NSArray<HKModel *> * _Nonnull models;
/// Initialize the backend in your AppDelegate
/// \param validateKey your API key, generated at http://developer.biodigital.com
///
/// \param secret your secret, also generated.  provide this optional variable to allow access to content associated with your account
///
- (nonnull instancetype)initWithValidateKey:(NSString * _Nonnull)validateKey secret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
/// Request models associated with your account from our server
- (void)getModels;
/// Get a list of Module objects by ICD Number
/// \param ICD String version of ICD number
///
///
/// returns:
/// [HKModel] an array of found Module objects, empty if none are found
- (void)findModelWithICD:(NSString * _Nonnull)ICD;
/// Returns true if a module is on disk and available for offline use
+ (BOOL)modelDownloadedWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Removes all stored BioDigital Human content from the device
+ (void)deleteStoredData;
/// Set the language, default is HumanLanguage.english
/// valid options are spanish and arabic
+ (void)setLanguageTo:(enum HumanLanguage)to;
/// return true if the language is Unicode (Chinese or Japanese)
+ (BOOL)isUnicodeLanguage SWIFT_WARN_UNUSED_RESULT;
/// Returns the json string for a module if it is on disk
+ (NSString * _Nonnull)getJsonStringForModule:(NSString * _Nonnull)forModule SWIFT_WARN_UNUSED_RESULT;
/// Returns the json string for a module if it is on disk
+ (NSData * _Nonnull)getJsonDataForModule:(NSString * _Nonnull)forModule SWIFT_WARN_UNUSED_RESULT;
/// Stops the backend service, this should ONLY be done when your app is going to stop running
- (void)stop;
/// Restarts the backend service, this should ONLY be done when your app is returning to the foreground
- (void)restart;
/// Request models associated with your account from our server
- (void)getModules;
/// Get a list of Module objects by ICD Number
/// \param ICD String version of ICD number
///
///
/// returns:
/// [HKModel] an array of found Module objects, empty if none are found
- (void)findModuleWithICD:(NSString * _Nonnull)ICD;
/// Returns true if a module is on disk and available for offline use
+ (BOOL)moduleDownloadedWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// callback methods for the HKServices delegate
SWIFT_PROTOCOL("_TtP8HumanKit18HKServicesDelegate_")
@protocol HKServicesDelegate
/// Callback when the validation process succeeds
- (void)onValidSDK;
/// Callback when the validation process has failed
- (void)onInvalidSDK;
@optional
/// Callback when a requested module fetch is complete
- (void)modelsLoaded;
/// Callback when a requested module fetch is complete
- (void)modulesLoaded;
@end


/// Timeline object
SWIFT_CLASS("_TtC8HumanKit10HKTimeline")
@interface HKTimeline : NSObject
/// The current animation time
@property (nonatomic) float currentTime;
/// The current animation duration
@property (nonatomic) float duration;
/// The current scene is animated, true or false
@property (nonatomic) BOOL playing;
/// The currently loaded Chapter to access title and description
@property (nonatomic, strong) HKChapter * _Nullable currentChapter;
/// A map of chapter IDs to HKChapter objects.
@property (nonatomic, copy) NSDictionary<NSString *, HKChapter *> * _Nonnull chapters;
/// An ordered list of chapter IDs
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull chapterList;
- (void)getTimelineInfo SWIFT_UNAVAILABLE_MSG("timeline info is directly accessible and always up to date");
/// Play the current scene’s animation from the beginning
- (void)play;
/// Pause the current scene’s animation
- (void)pause;
/// Unpause the current scene’s animation
- (void)unpause;
/// Jump to the current module’s next chapter
- (void)nextChapter;
/// Jump to the current module’s previous chapter
- (void)prevChapter;
/// Jump to the chapter with the given chapterID
- (void)moveToChapterWithChapterID:(NSString * _Nonnull)chapterID;
/// Jump to the given time in the current scene’s current animation
/// \param time animation offset in seconds
///
- (void)moveToTimeWithTime:(float)time;
/// Jump to the chapter with the given chapterID and play the animation in a loop
/// since:
/// SDK 2.0
- (void)loopWithChapterId:(NSString * _Nonnull)chapterId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// UI settings object
SWIFT_CLASS("_TtC8HumanKit4HKUI")
@interface HKUI : NSObject
/// an array of language names, in the appropriate language, for display
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull languageNames;)
+ (NSArray<NSString *> * _Nonnull)languageNames SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguageNames:(NSArray<NSString *> * _Nonnull)value;
/// an array of standard language codes
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull languageCodes;)
+ (NSArray<NSString *> * _Nonnull)languageCodes SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguageCodes:(NSArray<NSString *> * _Nonnull)value;
/// top or center color
@property (nonatomic, strong) UIColor * _Nonnull topColor;
/// bottom or outer color
@property (nonatomic, strong) UIColor * _Nonnull bottomColor;
/// background type .radial or .linear
@property (nonatomic) enum BackgroundOptions bgType;
/// color positions for top and bottom as percentage
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull colorStops;
/// A Boolean indicating if there is supposed to be a visible playPause button in the module
@property (nonatomic) BOOL hasPlayPause;
/// A Boolean indicating if there is supposed to be a visible timeline scrubber in the module
@property (nonatomic) BOOL hasScrubber;
///
/// returns:
/// the current language code
+ (NSString * _Nonnull)languageCode SWIFT_WARN_UNUSED_RESULT;
/// Change the background style with two specified colors
/// \param top Primary color
///
/// \param bottom Secondary color
///
/// \param bgType (optional) Background style (BackgroundOptions.radial or BackgroundOptions.linear, default is .radial)
///
- (void)setBackgroundColorWithTop:(UIColor * _Nonnull)top bottom:(UIColor * _Nonnull)bottom type:(enum BackgroundOptions)type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Enumerated language options for HKHuman
typedef SWIFT_ENUM(NSInteger, HumanLanguage, open) {
/// english
  HumanLanguageEnglish = 0,
/// spanish
  HumanLanguageSpanish = 1,
/// potuguese
  HumanLanguagePortuguese = 2,
/// french
  HumanLanguageFrench = 3,
/// italian
  HumanLanguageItalian = 4,
/// german
  HumanLanguageGerman = 5,
/// chinese
  HumanLanguageChinese = 6,
/// japanese
  HumanLanguageJapanese = 7,
};

/// Enumerated ui option flags you can set to true or false
typedef SWIFT_ENUM(NSInteger, HumanUIOptions, open) {
/// shows a panel of tools (xray, dissect, isolate, and cross section)
/// default is true
  HumanUIOptionsTools = 0,
/// show the current module/chapter title and description
/// default is true
  HumanUIOptionsInfo = 1,
/// show UI for interacting with animations (play/pause, timeline slider)
/// default is true
  HumanUIOptionsAnimation = 2,
/// show a help button for UI instruction panel
/// default is true
  HumanUIOptionsHelp = 3,
/// show a selectable tree of objects in the scene
/// default is false
  HumanUIOptionsObjectTree = 4,
/// show a button that resets the scene
  HumanUIOptionsReset = 5,
/// disable the link out from the BioDigital logo to our website
  HumanUIOptionsNolink = 6,
/// turn all of the widget UI elements OFF only. You need to turn them on individually.
  HumanUIOptionsAll = 7,
};





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif (defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__) || (defined(__i386__) && __i386__)
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HumanKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

/// Enumerated background option possible values
typedef SWIFT_ENUM(NSInteger, BackgroundOptions, open) {
/// a circular gradient from the center to the outside of the screen
  BackgroundOptionsRadial = 0,
/// a linear gradient from the top to the bottom of the screen
  BackgroundOptionsLinear = 1,
};




/// The HKAnnotation object represents an object annotation in the scene
SWIFT_CLASS("_TtC8HumanKit12HKAnnotation")
@interface HKAnnotation : NSObject
/// objectID of the annotated object
/// this is required, all annotations must be connected to an object
@property (nonatomic, copy) NSString * _Nonnull objectId;
/// annotation title
@property (nonatomic, copy) NSString * _Nonnull title;
/// annotation description text
@property (nonatomic, copy) NSString * _Nonnull text;
/// annotation ID for reference
@property (nonatomic, copy) NSString * _Nonnull annotationId;
/// world position [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull position;
/// screen position [x,y] of the annotation
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull canvasPosition;
/// label offset [x,y] from the object can be used to enhance visibility
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull labelOffset;
/// whether or not the annotation is currently visible
/// this will get set to false if the annotation moves off screen or is occluded
@property (nonatomic) BOOL shown;
/// whether or not the annotation is occludable
@property (nonatomic) BOOL occludable;
/// Create an HKAnnotation with the ID of its object
/// \param objectId Id of the attached object
///
- (nonnull instancetype)initWithObjectId:(NSString * _Nonnull)objectId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// HKAnnotations manages object annotations in the scene
/// since:
/// SDK 2.0
SWIFT_CLASS("_TtC8HumanKit13HKAnnotations")
@interface HKAnnotations : NSObject
/// A map of annotation IDs to HKAnnotation objects in the current scene
@property (nonatomic, copy) NSDictionary<NSString *, HKAnnotation *> * _Nonnull annotations;
/// Shows the annotations in the current scene
- (void)show;
/// Hides the annotations in the scene
/// This allows apps to draw native annotations over the view
- (void)hide;
/// Create an annotation in the scene with an HKAnnotation object.
/// since:
/// SDK 2.0
/// \param annotation set up an HKAnnotation object and pass it to this function to add it to the scene
///
- (void)createWithAnnotation:(HKAnnotation * _Nonnull)annotation;
/// Update an annotation in the scene with an updated HKAnnotation object.
/// since:
/// SDK 2.0
/// \param annotationId Id of the updated annotation to update in the scene
///
- (void)updateWithAnnotationId:(NSString * _Nonnull)annotationId;
/// Delete an annotation in the scene
/// since:
/// SDK 2.0
/// \param annotationId Id of the annotation to remove from the scene
///
- (void)destroyWithAnnotationId:(NSString * _Nonnull)annotationId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Camera object
SWIFT_CLASS("_TtC8HumanKit8HKCamera")
@interface HKCamera : NSObject
/// Camera position [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull eye;
/// Look vector [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull look;
/// Up vector [x,y,z]
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull up;
/// The current zoom factor of the camera
@property (nonatomic) double zoomFactor;
/// Get current camera information. (eye, look, up, and zoom)
/// Queries the scene asynchronously and sets local variables in the Camera object
/// Triggers camera.updated callback
/// Deprecated in API 2.0 as this information is directly accessible in this object and always up to date
- (void)getCameraInfo SWIFT_UNAVAILABLE_MSG("camera info is directly accessible and always up to date");
/// Reset camera to original position
/// since:
/// SDK 2.0
- (void)reset;
/// Pan camera by offset in world space.
/// \param x offset on x axis
///
/// \param y offset on y axis
///
/// \param z offset on z axis
///
- (void)panWithX:(float)x y:(float)y z:(float)z;
/// Zoom the camera in and out of its point of focus.
/// <ul>
///   <li>
///     : Zoom factor between 0 and 1
///   </li>
/// </ul>
- (void)zoom:(double)factor;
/// Orbit around camera’s current point of focus.
/// \param yaw Yaw angle (degrees)
///
/// \param pitch Pitch angle (degrees)
///
/// \param duration Time of orbit animation (seconds)
///
- (void)orbitWithYaw:(float)yaw pitch:(float)pitch duration:(float)duration;
/// Move the camera, all values are optional
/// \param eyeIn The new camera postion.
///
/// \param lookIn The new camera look vector.
///
/// \param upIn The new camera up vector.
///
/// \param animated If true, camera will animate from current position to new position, default is true
///
- (void)setWithEyeIn:(NSArray<NSNumber *> * _Nullable)eyeIn lookIn:(NSArray<NSNumber *> * _Nullable)lookIn upIn:(NSArray<NSNumber *> * _Nullable)upIn animated:(BOOL)animated;
/// Updates camera position.
/// \param eyeIn The new camera position
///
/// \param lookIn The new camera look vector.
///
/// \param upIn The new camera up vector.
///
/// \param animated If true, camera will animate from current position to new position
/// Deprecated for set()
///
- (void)updateCameraWithEyeIn:(NSArray<NSNumber *> * _Nonnull)eyeIn lookIn:(NSArray<NSNumber *> * _Nonnull)lookIn upIn:(NSArray<NSNumber *> * _Nonnull)upIn animated:(BOOL)animated SWIFT_DEPRECATED_MSG("Please use set(eyeIn:lookIn,upIn,animated:)");
/// Animates camera to object specified by its id.
/// \param objectId Object id specified by string
///
- (void)animateToObjectId:(NSString * _Nonnull)objectId;
/// Lock or unlock the camera rotation around the Y axis
/// attention:
/// This is no longer supported
/// \param lock boolean
///
- (void)lock:(BOOL)lock SWIFT_UNAVAILABLE_MSG("This is no longer supported");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// HKChapter object
SWIFT_CLASS("_TtC8HumanKit9HKChapter")
@interface HKChapter : NSObject
/// chapter title
@property (nonatomic, copy) NSString * _Nonnull title;
/// chapter description text
@property (nonatomic, copy) NSString * _Nonnull text;
/// chapter order, starts at 0
@property (nonatomic) NSInteger index;
/// true if this chapter is animated
/// since:
/// SDK 2.0
@property (nonatomic) BOOL animated;
/// true if this chapter contains audio
/// since:
/// SDK 2.0
@property (nonatomic) BOOL audio;
/// true if this chapter contains video
/// since:
/// SDK 2.0
@property (nonatomic) BOOL video;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;

/// HKColor object for use with scene.colorObject()
SWIFT_CLASS("_TtC8HumanKit7HKColor")
@interface HKColor : NSObject
/// tint color as UIColor
@property (nonatomic, strong) UIColor * _Nonnull tint;
/// saturation -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat saturation;
/// opacity 0.0 to 1.0, default is 1.0
@property (nonatomic) CGFloat opacity;
/// brightness -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat brightness;
/// contrast -1.0 to 1.0, default is 0.0
@property (nonatomic) CGFloat contrast;
/// Set all of the variables to random settings, for demonstration purposes
- (void)randomColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HKHumanDelegate;
@class HKScene;
@class HKTimeline;
@class HKUI;
@class UIView;
enum HumanUIOptions : NSInteger;

/// The BioDigital Human 3D View object and API
SWIFT_CLASS("_TtC8HumanKit7HKHuman")
@interface HKHuman : NSObject
/// The HKHumanDelegate object
/// <ul>
///   <li>
///     Set this to have access to the callback functions in your app
///   </li>
/// </ul>
@property (nonatomic, weak) id <HKHumanDelegate> _Nullable delegate;
/// HKScene object provides information and control of the 3D scene
@property (nonatomic, strong) HKScene * _Nonnull scene;
/// HKTimeline object controls Chapter navigation and animations
@property (nonatomic, strong) HKTimeline * _Nonnull timeline;
/// HKCamera object for manipulating the camera and reading camera information
@property (nonatomic, strong) HKCamera * _Nonnull camera;
/// HKUI object for setting and reading the UI parameters
@property (nonatomic, strong) HKUI * _Nonnull ui;
/// HKAnnotations object managing HKAnnotations in the scene
/// since:
/// SDK 2.0
@property (nonatomic, strong) HKAnnotations * _Nonnull annotations;
/// version of the 3D engine
@property (nonatomic, copy) NSString * _Nonnull version;
/// Initialize the Human Body with a view and the default UI options
/// note:
/// This is the recommended way to use HKHuman as of SDK 2.0
/// \param view the UIView to draw the 3D scene
///
- (nonnull instancetype)initWithView:(UIView * _Nonnull)view OBJC_DESIGNATED_INITIALIZER;
/// Set one UI variable to true or false
/// \param option a value from the enum HumanUIOptions
///
/// \param value true or false
///
- (void)setupUIWithOption:(enum HumanUIOptions)option value:(BOOL)value;
/// Loads a BioDigital Human 3D module.
/// \param model The moduleID string
///
/// \param callback A closure to run after the module is loaded
///
- (void)loadWithModel:(NSString * _Nonnull)model callback:(void (^ _Nonnull)(void))callback;
/// Unload a model if one is loaded
- (void)unload;
/// Disable user input
/// since:
/// SDK 2.0
- (void)disableInput;
/// Enable user input
/// since:
/// SDK 2.0
- (void)enableInput;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;

/// The optional delegate callback functions
SWIFT_PROTOCOL("_TtP8HumanKit15HKHumanDelegate_")
@protocol HKHumanDelegate
@optional
/// Callback when the scene metadata is accessible
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param initScene the title of the loaded scene
///
- (void)human:(HKHuman * _Nonnull)view initScene:(NSString * _Nonnull)initScene;
/// Callback when the current animation has updated
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param timelineUpdated the updated timeline object
///
- (void)human:(HKHuman * _Nonnull)view timelineUpdated:(HKTimeline * _Nonnull)timelineUpdated;
/// Callback when the current animation is finished playing
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param animationComplete always true
///
- (void)human:(HKHuman * _Nonnull)view animationComplete:(BOOL)animationComplete;
/// Callback when an object has been picked by the user
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
/// \param position the world position (x,y,z) of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectPicked:(NSString * _Nonnull)objectPicked position:(NSArray<NSNumber *> * _Nonnull)position;
/// Callback when an object has been selected
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectSelected:(NSString * _Nonnull)objectSelected;
/// Callback when an object has been deselected
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectId the ID of the selected object
///
- (void)human:(HKHuman * _Nonnull)view objectDeselected:(NSString * _Nonnull)objectDeselected;
/// Callback when a chapter has been loaded
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param chapterId the ID of the chapter, for lookup in the chapters map
///
- (void)human:(HKHuman * _Nonnull)view chapterTransition:(NSString * _Nonnull)chapterTransition;
/// Callback when the camera has been initialized or moved
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param cameraUpdated the updated HKCamera object
///
- (void)human:(HKHuman * _Nonnull)view cameraUpdated:(HKCamera * _Nonnull)cameraUpdated;
/// Callback when a xray mode is enabled or disabled
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param xrayEnabled Boolean indicating true for xray enabled or false for xray disabled
///
- (void)human:(HKHuman * _Nonnull)view xrayEnabled:(BOOL)xrayEnabled;
/// Callback when a call to scene.restore() has completed successfully
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param sceneRestored always true
///
- (void)human:(HKHuman * _Nonnull)view sceneRestored:(BOOL)sceneRestored;
/// Callback when visibility of scene objects has changed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectsShown a dictionary of object IDs and a boolean to indicate if the object is shown (true) or hidden (false)
///
- (void)human:(HKHuman * _Nonnull)view objectsShown:(NSDictionary<NSString *, NSNumber *> * _Nonnull)objectsShown;
/// Callback when the color of an object has been read from the scene
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param objectColor the ID of the object
///
/// \param color the color of the object
///
- (void)human:(HKHuman * _Nonnull)view objectColor:(NSString * _Nonnull)objectColor color:(HKColor * _Nonnull)color;
/// Callback when visibility of scene annotations has changed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationsShown a boolean to indicate if the annotations are shown (true) or hidden (false)
///
- (void)human:(HKHuman * _Nonnull)view annotationsShown:(BOOL)annotationsShown;
/// Callback when an annotation has been created
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationCreated the ID of the annotation
///
- (void)human:(HKHuman * _Nonnull)view annotationCreated:(NSString * _Nonnull)annotationCreated;
/// Callback when an annotation has been destroyed
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationDestroyed the ID of the annotation
///
- (void)human:(HKHuman * _Nonnull)view annotationDestroyed:(NSString * _Nonnull)annotationDestroyed;
/// Callback when an annotation has moved on the screen
/// since:
/// SDK 2.0
/// \param view the HKHuman object for this event
///
/// \param annotationUpdated the updated HKAnnotation object
///
- (void)human:(HKHuman * _Nonnull)view annotationUpdated:(HKAnnotation * _Nonnull)annotationUpdated;
/// Callback when a screenshot has been generated
/// \param image the UIImage screenshot
///
- (void)screenshotWithImage:(UIImage * _Nonnull)image;
/// Callback when the scene metadata is accessible
/// Deprecated in SDK 2.0
- (void)onInitMessage SWIFT_DEPRECATED_MSG("Please use human(_:initScene:)");
/// Callback when a chapter has been loaded
/// Deprecated in SDK 2.0
/// \param chapterId the ID of the chapter, for lookup in the chapters map
///
/// \param view the HKHuman object in which the transition occurred
///
- (void)onChapterTransitionWithChapterId:(NSString * _Nonnull)chapterId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:chapterTransition:)");
/// Callback when an object has been deselected
/// Deprecated in SDK 2.0
/// \param objectId the ID of the deselected object
///
/// \param view the HKHuman object in which the object was selected
///
- (void)onObjectDeselectedWithObjectId:(NSString * _Nonnull)objectId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:objectDeselected:)");
/// Callback when an object has been selected
/// Deprecated in SDK 2.0
/// \param objectId the ID of the selected object
///
/// \param view the HKHuman object in which the object was selected
///
- (void)onObjectSelectedWithObjectId:(NSString * _Nonnull)objectId view:(HKHuman * _Nonnull)view SWIFT_DEPRECATED_MSG("Please use human(_:objectSelected:)");
/// Callback when the current animation is finished playing
/// Deprecated in SDK 2.0
- (void)onAnimationComplete SWIFT_DEPRECATED_MSG("Please use human(_:animationComplete:)");
@end


/// HKModel object
SWIFT_CLASS("_TtC8HumanKit7HKModel")
@interface HKModel : NSObject
/// ID of the model.  example: production/maleAdult/flu.json
@property (nonatomic, copy) NSString * _Nonnull modelId;
/// model title
@property (nonatomic, copy) NSString * _Nonnull title;
/// model text description
@property (nonatomic, copy) NSString * _Nonnull text;
/// url of thumbnail image
@property (nonatomic, copy) NSString * _Nonnull thumbnail;
/// initialize an HKModel
/// \param modelId the model ID, will look like “production/maleAdult/flu” or “E3W2”
///
/// \param title the title of the model
///
/// \param text the text description of the model
///
/// \param thumb optionally include the name or location of the thumbnail image
///
- (nonnull instancetype)initWithModelId:(NSString * _Nonnull)modelId title:(NSString * _Nonnull)title text:(NSString * _Nonnull)text thumb:(NSString * _Nonnull)thumb OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// HKScene manages the current scene and the scene objects
SWIFT_CLASS("_TtC8HumanKit7HKScene")
@interface HKScene : NSObject
/// The title of the current loaded scene.
@property (nonatomic, copy) NSString * _Nonnull title;
/// The text  description of the current loaded scene.
@property (nonatomic, copy) NSString * _Nonnull text;
/// The text description of the current loaded scene, if it is broken into sections
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nonnull textSections;
/// A flat unordered list of visible objects in the current scene
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull objectIds;
/// A map of objectIDs to display names
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull objects;
/// Brings up the built-in iOS share UI with the current contents of the view
- (void)shareFrom:(CGRect)from;
/// Captures a screenshot and triggers the screenshot callback in HKHumanDelegate
- (void)screenshot;
/// Reset the scene objects to the current scene’s original state
/// note:
/// This does not reset the camera, there is a separate function for that
- (void)reset;
/// Hide a group of obects by object ID
/// Groups of objects can be hidden by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to hide
///
- (void)hideWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Show a group of obects by object ID
/// Groups of objects can be shown by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to show
///
- (void)showWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Isolate a group of obects by object ID
/// Groups of objects can be shown by passing more than one objectID or by passing a “group node” ID
/// since:
/// SDK 2.0
/// \param objectIds An array of object IDs to isolate
///
- (void)isolateWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Select a group of objects programatically
/// \param objectIds An array of object IDs to select
///
- (void)selectWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// Deselect all objects in the scene
- (void)undoSelections;
/// Change the highlight color
/// \param color Selected objects are yellow by default, set this to use a different color
///
- (void)setHighlightColorWithColor:(UIColor * _Nonnull)color;
/// Change the object highlight color back to the original yellow color
- (void)resetHighlightColor;
/// Disable object highlighting
- (void)disableHighlight;
/// Enable object highlighting
- (void)enableHighlight;
/// Highlight an object even if highlight is disabled for the user
/// \param objectIds object to highlight
///
- (void)highlightWithObjectIds:(NSArray<NSString *> * _Nonnull)objectIds;
/// unhighlight an object
/// \param objectId object to unhighlight
///
- (void)unhighlightWithObjectId:(NSString * _Nonnull)objectId;
/// Prevent objects from being selected
- (void)disablePicking;
/// Allow objects to be selected
- (void)enablePicking;
/// Enables labels to appear when an object is selected, this is the default behavior, unless disabled
- (void)showLabels;
/// Hides all object labels and disables future labels from appearing on selected objects
- (void)hideLabels;
/// Turn xray mode ON or OFF in the current scene
/// \param enabled A boolean to turn xray mode ON or OFF
///
- (void)xray:(BOOL)enabled;
/// Get an object’s screen position
/// \param objectID A valid object ID string
///
///
/// returns:
/// the screen position of the center of the object with the given ID as [x,y]
- (NSArray<NSNumber *> * _Nonnull)getObjectPositionWithObjectID:(NSString * _Nonnull)objectID SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE_MSG("this is no longer supported.  please contact BioDigital if you require this functionality.");
/// Set the color of an object
- (void)colorWithObjectId:(NSString * _Nonnull)objectId color:(HKColor * _Nonnull)color;
/// Unset the color of a scene object
/// \param objectId object ID to uncolor
///
- (void)uncolorWithObjectId:(NSString * _Nonnull)objectId;
/// Get the color of a scene object
/// since:
/// SDK 2.0
/// Calls human(_:colorObject:color:) on success
/// \param objectId object ID to uncolor
///
- (void)getColorWithObjectId:(NSString * _Nonnull)objectId;
/// Move an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param translate [x,y,z] array amount to move the object]
///
- (void)translateObjectWithObjectId:(NSString * _Nonnull)objectId translate:(NSArray<NSNumber *> * _Nonnull)translate;
/// Rotate an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param rotate [x,y,z] array amount to rotate the object]
///
- (void)rotateObjectWithObjectId:(NSString * _Nonnull)objectId rotate:(NSArray<NSNumber *> * _Nonnull)rotate;
/// Scale an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param scale [x,y,z] array amount to scale the object]
///
- (void)scaleObjectWithObjectId:(NSString * _Nonnull)objectId scale:(NSArray<NSNumber *> * _Nonnull)scale;
/// Pivot an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param pivot [x,y,z] array amount to rotate the object]
///
- (void)pivotObjectWithObjectId:(NSString * _Nonnull)objectId pivot:(NSArray<NSNumber *> * _Nonnull)pivot;
/// Move an object in 3D space
/// since:
/// SDK 2.0
/// \param objectid object to transform
///
/// \param translate [x,y,z] array amount to move the object]
///
/// \param rotate [x,y,z] array amount to rotate the object]
///
/// \param scale [x,y,z] array amount to scale the object]
///
/// \param pivot [x,y,z] array amount to rotate the object]
///
- (void)transformObjectWithObjectId:(NSString * _Nonnull)objectId translate:(NSArray<NSNumber *> * _Nonnull)translate rotate:(NSArray<NSNumber *> * _Nonnull)rotate scale:(NSArray<NSNumber *> * _Nonnull)scale pivot:(NSArray<NSNumber *> * _Nonnull)pivot;
/// Capture the current state of the scene
/// since:
/// SDK 2.0
- (void)capture;
/// Restore the scene from the previous capture
/// Calls human(_:sceneRestored:) on success
/// since:
/// SDK 2.0
- (void)restore;
/// Select an object programatically
/// \param objectID the object you want to select
/// Deprecated in SDK 2.0.  Please use selectObjects(objectIds:) instead
///
- (void)selectObjectWithObjectID:(NSString * _Nonnull)objectID SWIFT_DEPRECATED_MSG("Please use select(objectIds:) instead");
/// Select an object programatically     - Parameter objectID: the object you want to select
/// Deprecated in SDK 2.0.  Please use selectObjects(objectIds:) instead
- (void)selectObjectWithGroupWithObjectID:(NSString * _Nonnull)objectID group:(NSArray<NSString *> * _Nonnull)group SWIFT_DEPRECATED_MSG("Please use select(objectIds:) instead");
/// Turn isolate mode ON or OFF in the current scene
/// This will isolate any selected objects and set the SDK to isolate any user selected object
/// \param enabled A boolean to turn isolate mode ON or OFF
///
- (void)isolate:(BOOL)enabled SWIFT_DEPRECATED_MSG("Please use isolate(objectIds:)");
/// Turn dissect mode ON or OFF in the current scene
/// \param enabled A boolean to turn dissect mode ON or OFF
///
- (void)dissect:(BOOL)enabled SWIFT_DEPRECATED_MSG("Please use hide(objectIds:)");
/// Undo the last dissect
/// Deprecated in API 2.0 use showObjects(objIds:) instead
- (void)undo SWIFT_DEPRECATED_MSG("Please use show(objectIds:)");
/// Set the color of an object
- (void)colorObjectWithId:(NSString * _Nonnull)id color:(HKColor * _Nonnull)color SWIFT_DEPRECATED_MSG("", "colorWithObjectId:color:");
/// Unset the color of a scene object
- (void)uncolorObjectWithId:(NSString * _Nonnull)id SWIFT_DEPRECATED_MSG("", "uncolorWithObjectId:");
/// unHighlight an object
/// \param objectId object to unhighlight
///
- (void)unhighlightObjectWithObjectid:(NSString * _Nonnull)objectid;
/// Check if an object is Xray
/// Removed in API 2.0, use getColor(id:) instead
- (BOOL)isXrayWithObjectID:(NSString * _Nonnull)objectID SWIFT_WARN_UNUSED_RESULT SWIFT_UNAVAILABLE_MSG("Please use getColor(objectId:) instead");
/// Set an object to Xray
/// Removed in API 2.0 - Set the object’s color instead
/// Our ’xray” color is brightness = 0.55, saturation = -1, and tint is UIColor(red:0.0, green: 0.0, blue: 0.0, alpha: 1.0)
- (void)setXrayWithObjectID:(NSString * _Nonnull)objectID enable:(BOOL)enable SWIFT_UNAVAILABLE_MSG("Please use colorObject instead");
/// Set an object to unpickable
/// Removed in API 2.0 - this is no longer supported
- (void)setPickableWithObjectID:(NSString * _Nonnull)objectID enable:(BOOL)enable SWIFT_UNAVAILABLE_MSG("This is not currently supported");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HKServicesDelegate;
enum HumanLanguage : NSInteger;

/// The BioDigital Human backend services
SWIFT_CLASS("_TtC8HumanKit10HKServices")
@interface HKServices : NSObject
/// Set the delegate for access to the callback functions
@property (nonatomic, weak) id <HKServicesDelegate> _Nullable delegate;
/// Modules fetched from the BioDigital servers are stored here
/// Providing a secret to the init function will trigger a fetch of modules associated with your account, the modulesLoaded callback will alert you when the module array is ready
@property (nonatomic, copy) NSArray<HKModel *> * _Nonnull models;
/// Initialize the backend in your AppDelegate
/// \param validateKey your API key, generated at http://developer.biodigital.com
///
/// \param secret your secret, also generated.  provide this optional variable to allow access to content associated with your account
///
- (nonnull instancetype)initWithValidateKey:(NSString * _Nonnull)validateKey secret:(NSString * _Nonnull)secret OBJC_DESIGNATED_INITIALIZER;
/// Request models associated with your account from our server
- (void)getModels;
/// Get a list of Module objects by ICD Number
/// \param ICD String version of ICD number
///
///
/// returns:
/// [HKModel] an array of found Module objects, empty if none are found
- (void)findModelWithICD:(NSString * _Nonnull)ICD;
/// Returns true if a module is on disk and available for offline use
+ (BOOL)modelDownloadedWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Removes all stored BioDigital Human content from the device
+ (void)deleteStoredData;
/// Set the language, default is HumanLanguage.english
/// valid options are spanish and arabic
+ (void)setLanguageTo:(enum HumanLanguage)to;
/// return true if the language is Unicode (Chinese or Japanese)
+ (BOOL)isUnicodeLanguage SWIFT_WARN_UNUSED_RESULT;
/// Returns the json string for a module if it is on disk
+ (NSString * _Nonnull)getJsonStringForModule:(NSString * _Nonnull)forModule SWIFT_WARN_UNUSED_RESULT;
/// Returns the json string for a module if it is on disk
+ (NSData * _Nonnull)getJsonDataForModule:(NSString * _Nonnull)forModule SWIFT_WARN_UNUSED_RESULT;
/// Stops the backend service, this should ONLY be done when your app is going to stop running
- (void)stop;
/// Restarts the backend service, this should ONLY be done when your app is returning to the foreground
- (void)restart;
/// Request models associated with your account from our server
- (void)getModules;
/// Get a list of Module objects by ICD Number
/// \param ICD String version of ICD number
///
///
/// returns:
/// [HKModel] an array of found Module objects, empty if none are found
- (void)findModuleWithICD:(NSString * _Nonnull)ICD;
/// Returns true if a module is on disk and available for offline use
+ (BOOL)moduleDownloadedWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// callback methods for the HKServices delegate
SWIFT_PROTOCOL("_TtP8HumanKit18HKServicesDelegate_")
@protocol HKServicesDelegate
/// Callback when the validation process succeeds
- (void)onValidSDK;
/// Callback when the validation process has failed
- (void)onInvalidSDK;
@optional
/// Callback when a requested module fetch is complete
- (void)modelsLoaded;
/// Callback when a requested module fetch is complete
- (void)modulesLoaded;
@end


/// Timeline object
SWIFT_CLASS("_TtC8HumanKit10HKTimeline")
@interface HKTimeline : NSObject
/// The current animation time
@property (nonatomic) float currentTime;
/// The current animation duration
@property (nonatomic) float duration;
/// The current scene is animated, true or false
@property (nonatomic) BOOL playing;
/// The currently loaded Chapter to access title and description
@property (nonatomic, strong) HKChapter * _Nullable currentChapter;
/// A map of chapter IDs to HKChapter objects.
@property (nonatomic, copy) NSDictionary<NSString *, HKChapter *> * _Nonnull chapters;
/// An ordered list of chapter IDs
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull chapterList;
- (void)getTimelineInfo SWIFT_UNAVAILABLE_MSG("timeline info is directly accessible and always up to date");
/// Play the current scene’s animation from the beginning
- (void)play;
/// Pause the current scene’s animation
- (void)pause;
/// Unpause the current scene’s animation
- (void)unpause;
/// Jump to the current module’s next chapter
- (void)nextChapter;
/// Jump to the current module’s previous chapter
- (void)prevChapter;
/// Jump to the chapter with the given chapterID
- (void)moveToChapterWithChapterID:(NSString * _Nonnull)chapterID;
/// Jump to the given time in the current scene’s current animation
/// \param time animation offset in seconds
///
- (void)moveToTimeWithTime:(float)time;
/// Jump to the chapter with the given chapterID and play the animation in a loop
/// since:
/// SDK 2.0
- (void)loopWithChapterId:(NSString * _Nonnull)chapterId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// UI settings object
SWIFT_CLASS("_TtC8HumanKit4HKUI")
@interface HKUI : NSObject
/// an array of language names, in the appropriate language, for display
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull languageNames;)
+ (NSArray<NSString *> * _Nonnull)languageNames SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguageNames:(NSArray<NSString *> * _Nonnull)value;
/// an array of standard language codes
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull languageCodes;)
+ (NSArray<NSString *> * _Nonnull)languageCodes SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguageCodes:(NSArray<NSString *> * _Nonnull)value;
/// top or center color
@property (nonatomic, strong) UIColor * _Nonnull topColor;
/// bottom or outer color
@property (nonatomic, strong) UIColor * _Nonnull bottomColor;
/// background type .radial or .linear
@property (nonatomic) enum BackgroundOptions bgType;
/// color positions for top and bottom as percentage
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull colorStops;
/// A Boolean indicating if there is supposed to be a visible playPause button in the module
@property (nonatomic) BOOL hasPlayPause;
/// A Boolean indicating if there is supposed to be a visible timeline scrubber in the module
@property (nonatomic) BOOL hasScrubber;
///
/// returns:
/// the current language code
+ (NSString * _Nonnull)languageCode SWIFT_WARN_UNUSED_RESULT;
/// Change the background style with two specified colors
/// \param top Primary color
///
/// \param bottom Secondary color
///
/// \param bgType (optional) Background style (BackgroundOptions.radial or BackgroundOptions.linear, default is .radial)
///
- (void)setBackgroundColorWithTop:(UIColor * _Nonnull)top bottom:(UIColor * _Nonnull)bottom type:(enum BackgroundOptions)type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Enumerated language options for HKHuman
typedef SWIFT_ENUM(NSInteger, HumanLanguage, open) {
/// english
  HumanLanguageEnglish = 0,
/// spanish
  HumanLanguageSpanish = 1,
/// potuguese
  HumanLanguagePortuguese = 2,
/// french
  HumanLanguageFrench = 3,
/// italian
  HumanLanguageItalian = 4,
/// german
  HumanLanguageGerman = 5,
/// chinese
  HumanLanguageChinese = 6,
/// japanese
  HumanLanguageJapanese = 7,
};

/// Enumerated ui option flags you can set to true or false
typedef SWIFT_ENUM(NSInteger, HumanUIOptions, open) {
/// shows a panel of tools (xray, dissect, isolate, and cross section)
/// default is true
  HumanUIOptionsTools = 0,
/// show the current module/chapter title and description
/// default is true
  HumanUIOptionsInfo = 1,
/// show UI for interacting with animations (play/pause, timeline slider)
/// default is true
  HumanUIOptionsAnimation = 2,
/// show a help button for UI instruction panel
/// default is true
  HumanUIOptionsHelp = 3,
/// show a selectable tree of objects in the scene
/// default is false
  HumanUIOptionsObjectTree = 4,
/// show a button that resets the scene
  HumanUIOptionsReset = 5,
/// disable the link out from the BioDigital logo to our website
  HumanUIOptionsNolink = 6,
/// turn all of the widget UI elements OFF only. You need to turn them on individually.
  HumanUIOptionsAll = 7,
};





#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
